### PR TITLE
Cleanup MolReader

### PR DESCRIPTION
**Pull request by skearnes**
Significant cleanup of the conformer combination routine in MolReader.

### CODE REVIEW

**Comment by rbharath** [comment]
Can you add tests for the new methods?

**Comment by skearnes** [comment]
@rbharath I've done a major refactoring of the serial code. Everything is class-based, and there is an extensive test suite for I/O operations. One of my favorite additions is an **iter** method and a context manager for the base `MolIO` class, so you can write code like:

``` python
from rdkit_utils import serial

with serial.MolReader().open(filename) as reader:
    for mol in reader:
        ...
```

Some of the tests are not as rigorous as I would like because I can't always make the output of `mol.ToBinary()` agree with reference molecules. However, I have written substitute tests that compare the SDF output from rdkit that will have to suffice until I can figure out what's going on.

Sorry there are so many commits. I can rebase if it helps with the review.

**Comment by rbharath** [comment]
LGTM, but it looks like the Travis CI is failing. Feel free to merge once this issue is worked out. (PS, I like the addition of **enter** and **exit** methods).

**Comment by skearnes** [comment]
@rbharath Thanks. The error was an unused import that pyflakes caught :)

**Pull request merged**
